name: CI

on:
  push:
    branches: [ ci/migrate-to-gh-actions ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: cimg/node:20.18
    steps:
      - uses: actions/checkout@v4


      - name: Install dependencies
        run: make install

      - name: Save dependencies cache for future builds
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: dependencies-cache-${{ hashFiles('package.json') }}

      - name: Save app bundle (repo + dependencies) for downstream jobs
        uses: actions/cache/save@v3
        with:
          path: .
          key: bundle-cache-${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies cache from previous builds
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: dependencies-cache-${{ hashFiles('package.json') }}

      - name: Run linter
        run: yarn lint

  test:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest
    container: cimg/node:20.18
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
        env:
          ES_JAVA_OPTS: -Xms256m -Xmx256m
          discovery.type: single-node
          cluster.name: datashare
          http.cors.enabled: "true"
          http.cors.allow-origin: "*"
          http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
          options: >-
            --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 9200:9200
    steps:
      - uses: actions/checkout@v4

      - name: Restore app bundle cache (repo + dependencies) from the `build` job
        uses: actions/cache/restore@v3
        with:
          path: .
          key: bundle-cache-${{ github.sha }}
      - name: Run unit tests
        run: yarn test:unit --silent --minWorkers 1 --maxWorkers 2
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Make distribution
        run: make dist
