name: CI

on:
  push:
    branches:
      - ci/migrate-to-gh-actions
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: dependencies-cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: make install

      - name: Save dependencies cache for future builds
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: bundle-cache-${{ github.sha }}

      - name: Save app bundle (repo + dependencies) for downstream jobs
        uses: actions/cache@v3
        with:
          path: ~/datashare-client
          key: bundle-cache-${{ github.sha }}


  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms256m -Xmx256m
          # CORS
          http.cors.enabled: "true"
          http.cors.allow-origin: "*"
          http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Restore app bundle (repo + dependencies) from the `build` job
        uses: actions/cache@v3
        with:
          path: ~/datashare-client
          key: bundle-cache-${{ github.sha }}

      - name: Run unit tests
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn test:unit --silent --minWorkers 1 --maxWorkers 2 tests/unit/specs/components/Search/SearchBar/SearchBar.spec.js

      - name: Make distribution
        run: make dist

