# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  publish:
    if: github.ref == 'refs/heads/feat/new-design'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build storybook artifacts
        run: yarn build:storybook

      - name: Upload storybook artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy artifact to Github Pages
        uses: actions/deploy-pages@v4


