name: Datashare build, tests and docs

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.2'
          cache: 'yarn'

      - name: Install dependencies
        run: make install

  storybook:
    name: Publish Storybook
    needs: prepare
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.2'
          cache: 'yarn'

      - name: Install dependencies
        run: make install

      - name: Generate doc pages
        run: yarn doc

      - name: Upload storybook artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy artifact to Github Pages
        uses: actions/deploy-pages@v4

  test:
    name: Unit tests
    needs: prepare
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
        env:
          ES_JAVA_OPTS: -Xms256m -Xmx256m
          discovery.type: single-node
          cluster.name: datashare
          http.compression: false
          http.cors.enabled: true
          http.cors.allow-origin: "*"
          http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
          indices.query.bool.max_clause_count: 20000
        options: >-
            --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 9200:9200
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.2'
          cache: 'yarn'

      - name: Install dependencies
        run: make install

      - name: Run unit tests
        run: yarn test:unit --silent --minWorkers 1 --maxWorkers 2
        env:
          VITE_ES_HOST: http://localhost:9200
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Make distribution
        run: make dist

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.2'
          cache: 'yarn'

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: yarn lint